// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Task struct {
	ID          uuid.UUID
	CreatedAt   sql.NullTime
	CompletedAt sql.NullTime
	Status      string
	Link        sql.NullString
}
